### PR TITLE
Whitelist os-upgrade.service

### PR DESCRIPTION
**Pull request by george-angel**

### CODE REVIEW

**Comment by tamas-molnar** [comment]
+1

**Comment by kovacshuni** [comment]
+1

**Comment by ghost** [comment]
can't the app discover for itself whether these are timer based somehow? (I guess ppl looked for that already?)

**Comment by george-angel** [comment]
:) Its not timer based, its manually triggered.

**Comment by ghost** [comment]
shame. can we somehow add some metadata to out services themselves to whitelist them in this context?

**Comment by george-angel** [comment]
Probably, yeah

**Pull request merged**
